arch:
  - amd64
  - ppc64le
language: python
python:
  - "2.7"
  - "3.5"

before_install:
  - ./download_etcd.sh 2.3.7
  - pip install --upgrade setuptools

# command to install dependencies
install:
  - pip install coveralls
  - pip install coverage
  - python bootstrap.py
  - bin/buildout

# command to run tests
script:
  PATH=$PATH:./bin coverage run --source=src/etcd --omit="src/etcd/tests/*" bin/test

after_success: coveralls
# Add env var to detect it during build
env: TRAVIS=True
